List_problem_cat <- list("Total"= c("Total_PAI", "Total_Staff", "Total_a_counsel_and_advice", 
                                    "Total_b_limited_action", "Total_f_negotiated_settlement_w_o_litigation", 
                                    "Total_g_negotiated_settlement_w_litigation", "Total_h_agency_decision", 
                                    "Total_ia_court_decision_uncontested", "Total_ib_court_decision_contested", 
                                    "Total_ic_court_decision_appeals", "Total_k_other_closure_methods", 
                                    "Total_l_extensive_services"),
                         
                         "Consumer" = c("Consumer_Staff", "Consumer_PAI", "Total_Consumer", 
                                        "cases_closed_limited_Consumer_Staff", 
                                        "cases_closed_limited_Consumer_PAI", 
                                        "cases_closed_extended_Consumer_Staff", 
                                        "cases_closed_extended_Consumer_PAI", 
                                        "cases_closed_contested_Consumer_Staff", 
                                        "cases_closed_contested_Consumer_PAI", 
                                        "a_counsel_and_advice_Consumer_Staff", 
                                        "a_counsel_and_advice_Consumer_PAI", 
                                        "b_limited_action_Consumer_Staff", 
                                        "b_limited_action_Consumer_PAI", 
                                        "f_negotiated_settlement_w_o_litigation_Consumer_Staff", 
                                        "f_negotiated_settlement_w_o_litigation_Consumer_PAI", 
                                        "g_negotiated_settlement_w_litigation_Consumer_Staff", 
                                        "g_negotiated_settlement_w_litigation_Consumer_PAI", 
                                        "h_agency_decision_Consumer_Staff", 
                                        "h_agency_decision_Consumer_PAI", 
                                        "ia_court_decision_uncontested_Consumer_Staff", 
                                        "ia_court_decision_uncontested_Consumer_PAI", 
                                        "ib_court_decision_contested_Consumer_Staff", 
                                        "ib_court_decision_contested_Consumer_PAI", 
                                        "ic_court_decision_appeals_Consumer_Staff", 
                                        "ic_court_decision_appeals_Consumer_PAI", 
                                        "k_other_closure_methods_Consumer_Staff", 
                                        "k_other_closure_methods_Consumer_PAI", 
                                        "l_extensive_services_Consumer_Staff", 
                                        "l_extensive_services_Consumer_PAI",
                                        "cases_closed_limited_Consumer", "a_counsel_and_advice_Consumer", 
                                        "b_limited_action_Consumer", "cases_closed_extended_Consumer", 
                                        "f_negotiated_settlement_w_o_litigation_Consumer", 
                                        "g_negotiated_settlement_w_litigation_Consumer", 
                                        "h_agency_decision_Consumer", "ia_court_decision_uncontested_Consumer", 
                                        "ib_court_decision_contested_Consumer", "ic_court_decision_appeals_Consumer",
                                        "k_other_closure_methods_Consumer", "l_extensive_services_Consumer", 
                                        "cases_closed_contested_Consumer"),
                         
                         "Education" = c("Education_Staff", "Education_PAI", "Total_Education", 
                                         "cases_closed_limited_Education_Staff", 
                                         "cases_closed_limited_Education_PAI", 
                                         "cases_closed_extended_Education_Staff", 
                                         "cases_closed_extended_Education_PAI", 
                                         "cases_closed_contested_Education_Staff", 
                                         "cases_closed_contested_Education_PAI", 
                                         "a_counsel_and_advice_Education_Staff", 
                                         "a_counsel_and_advice_Education_PAI", 
                                         "b_limited_action_Education_Staff", 
                                         "b_limited_action_Education_PAI", 
                                         "f_negotiated_settlement_w_o_litigation_Education_Staff", 
                                         "f_negotiated_settlement_w_o_litigation_Education_PAI", 
                                         "g_negotiated_settlement_w_litigation_Education_Staff", 
                                         "g_negotiated_settlement_w_litigation_Education_PAI", 
                                         "h_agency_decision_Education_Staff", 
                                         "h_agency_decision_Education_PAI", 
                                         "ia_court_decision_uncontested_Education_Staff", 
                                         "ia_court_decision_uncontested_Education_PAI", 
                                         "ib_court_decision_contested_Education_Staff", 
                                         "ib_court_decision_contested_Education_PAI", 
                                         "ic_court_decision_appeals_Education_Staff", 
                                         "ic_court_decision_appeals_Education_PAI", 
                                         "k_other_closure_methods_Education_Staff", 
                                         "k_other_closure_methods_Education_PAI", 
                                         "l_extensive_services_Education_Staff", 
                                         "l_extensive_services_Education_PAI",
                                         "cases_closed_limited_Education", "a_counsel_and_advice_Education", 
                                         "b_limited_action_Education", "cases_closed_extended_Education", 
                                         "f_negotiated_settlement_w_o_litigation_Education", 
                                         "g_negotiated_settlement_w_litigation_Education", 
                                         "h_agency_decision_Education", "ia_court_decision_uncontested_Education", 
                                         "ib_court_decision_contested_Education", "ic_court_decision_appeals_Education",
                                         "k_other_closure_methods_Education", "l_extensive_services_Education", 
                                         "cases_closed_contested_Education"),
                         
                         "Employment" = c("Employment_Staff", "Employment_PAI", "Total_Employment", 
                                          "cases_closed_limited_Employment_Staff", 
                                          "cases_closed_limited_Employment_PAI", 
                                          "cases_closed_extended_Employment_Staff", 
                                          "cases_closed_extended_Employment_PAI", 
                                          "cases_closed_contested_Employment_Staff", 
                                          "cases_closed_contested_Employment_PAI", 
                                          "a_counsel_and_advice_Employment_Staff", 
                                          "a_counsel_and_advice_Employment_PAI", 
                                          "b_limited_action_Employment_Staff", 
                                          "b_limited_action_Employment_PAI", 
                                          "f_negotiated_settlement_w_o_litigation_Employment_Staff", 
                                          "f_negotiated_settlement_w_o_litigation_Employment_PAI", 
                                          "g_negotiated_settlement_w_litigation_Employment_Staff", 
                                          "g_negotiated_settlement_w_litigation_Employment_PAI", 
                                          "h_agency_decision_Employment_Staff", 
                                          "h_agency_decision_Employment_PAI", 
                                          "ia_court_decision_uncontested_Employment_Staff", 
                                          "ia_court_decision_uncontested_Employment_PAI", 
                                          "ib_court_decision_contested_Employment_Staff", 
                                          "ib_court_decision_contested_Employment_PAI", 
                                          "ic_court_decision_appeals_Employment_Staff", 
                                          "ic_court_decision_appeals_Employment_PAI", 
                                          "k_other_closure_methods_Employment_Staff", 
                                          "k_other_closure_methods_Employment_PAI", 
                                          "l_extensive_services_Employment_Staff", 
                                          "l_extensive_services_Employment_PAI",
                                          "cases_closed_limited_Employment", "a_counsel_and_advice_Employment", 
                                          "b_limited_action_Employment", "cases_closed_extended_Employment", 
                                          "f_negotiated_settlement_w_o_litigation_Employment", 
                                          "g_negotiated_settlement_w_litigation_Employment", 
                                          "h_agency_decision_Employment", "ia_court_decision_uncontested_Employment", 
                                          "ib_court_decision_contested_Employment", "ic_court_decision_appeals_Employment",
                                          "k_other_closure_methods_Employment", "l_extensive_services_Employment", 
                                          "cases_closed_contested_Employment"),
                         
                         "Family" = c("Family_Staff", "Family_PAI", "Total_Family", 
                                      "cases_closed_limited_Family_Staff", 
                                      "cases_closed_limited_Family_PAI", 
                                      "cases_closed_extended_Family_Staff", 
                                      "cases_closed_extended_Family_PAI", 
                                      "cases_closed_contested_Family_Staff", 
                                      "cases_closed_contested_Family_PAI", 
                                      "a_counsel_and_advice_Family_Staff", 
                                      "a_counsel_and_advice_Family_PAI", 
                                      "b_limited_action_Family_Staff", 
                                      "b_limited_action_Family_PAI", 
                                      "f_negotiated_settlement_w_o_litigation_Family_Staff", 
                                      "f_negotiated_settlement_w_o_litigation_Family_PAI", 
                                      "g_negotiated_settlement_w_litigation_Family_Staff", 
                                      "g_negotiated_settlement_w_litigation_Family_PAI", 
                                      "h_agency_decision_Family_Staff", 
                                      "h_agency_decision_Family_PAI", 
                                      "ia_court_decision_uncontested_Family_Staff", 
                                      "ia_court_decision_uncontested_Family_PAI", 
                                      "ib_court_decision_contested_Family_Staff", 
                                      "ib_court_decision_contested_Family_PAI", 
                                      "ic_court_decision_appeals_Family_Staff", 
                                      "ic_court_decision_appeals_Family_PAI", 
                                      "k_other_closure_methods_Family_Staff", 
                                      "k_other_closure_methods_Family_PAI", 
                                      "l_extensive_services_Family_Staff", 
                                      "l_extensive_services_Family_PAI",
                                      "cases_closed_limited_Family", "a_counsel_and_advice_Family", 
                                      "b_limited_action_Family", "cases_closed_extended_Family", 
                                      "f_negotiated_settlement_w_o_litigation_Family", 
                                      "g_negotiated_settlement_w_litigation_Family", 
                                      "h_agency_decision_Family", "ia_court_decision_uncontested_Family", 
                                      "ib_court_decision_contested_Family", "ic_court_decision_appeals_Family",
                                      "k_other_closure_methods_Family", "l_extensive_services_Family", 
                                      "cases_closed_contested_Family"),
                         
                         "Health" = c("Health_Staff", "Health_PAI", "Total_Health", 
                                      "cases_closed_limited_Health_Staff", 
                                      "cases_closed_limited_Health_PAI", 
                                      "cases_closed_extended_Health_Staff", 
                                      "cases_closed_extended_Health_PAI", 
                                      "cases_closed_contested_Health_Staff", 
                                      "cases_closed_contested_Health_PAI", 
                                      "a_counsel_and_advice_Health_Staff", 
                                      "a_counsel_and_advice_Health_PAI", 
                                      "b_limited_action_Health_Staff", 
                                      "b_limited_action_Health_PAI", 
                                      "f_negotiated_settlement_w_o_litigation_Health_Staff", 
                                      "f_negotiated_settlement_w_o_litigation_Health_PAI", 
                                      "g_negotiated_settlement_w_litigation_Health_Staff", 
                                      "g_negotiated_settlement_w_litigation_Health_PAI", 
                                      "h_agency_decision_Health_Staff", 
                                      "h_agency_decision_Health_PAI", 
                                      "ia_court_decision_uncontested_Health_Staff", 
                                      "ia_court_decision_uncontested_Health_PAI", 
                                      "ib_court_decision_contested_Health_Staff", 
                                      "ib_court_decision_contested_Health_PAI", 
                                      "ic_court_decision_appeals_Health_Staff", 
                                      "ic_court_decision_appeals_Health_PAI", 
                                      "k_other_closure_methods_Health_Staff", 
                                      "k_other_closure_methods_Health_PAI", 
                                      "l_extensive_services_Health_Staff", 
                                      "l_extensive_services_Health_PAI",
                                      "cases_closed_limited_Health", "a_counsel_and_advice_Health", 
                                      "b_limited_action_Health", "cases_closed_extended_Health", 
                                      "f_negotiated_settlement_w_o_litigation_Health", 
                                      "g_negotiated_settlement_w_litigation_Health", 
                                      "h_agency_decision_Health", "ia_court_decision_uncontested_Health", 
                                      "ib_court_decision_contested_Health", "ic_court_decision_appeals_Health",
                                      "k_other_closure_methods_Health", "l_extensive_services_Health", 
                                      "cases_closed_contested_Health"),
                         
                         "Housing" = c("Housing_Staff", "Housing_PAI", "Total_Housing", 
                                       "cases_closed_limited_Housing_Staff", 
                                       "cases_closed_limited_Housing_PAI", 
                                       "cases_closed_extended_Housing_Staff", 
                                       "cases_closed_extended_Housing_PAI", 
                                       "cases_closed_contested_Housing_Staff", 
                                       "cases_closed_contested_Housing_PAI", 
                                       "a_counsel_and_advice_Housing_Staff", 
                                       "a_counsel_and_advice_Housing_PAI", 
                                       "b_limited_action_Housing_Staff", 
                                       "b_limited_action_Housing_PAI", 
                                       "f_negotiated_settlement_w_o_litigation_Housing_Staff", 
                                       "f_negotiated_settlement_w_o_litigation_Housing_PAI", 
                                       "g_negotiated_settlement_w_litigation_Housing_Staff", 
                                       "g_negotiated_settlement_w_litigation_Housing_PAI", 
                                       "h_agency_decision_Housing_Staff", 
                                       "h_agency_decision_Housing_PAI", 
                                       "ia_court_decision_uncontested_Housing_Staff", 
                                       "ia_court_decision_uncontested_Housing_PAI", 
                                       "ib_court_decision_contested_Housing_Staff", 
                                       "ib_court_decision_contested_Housing_PAI", 
                                       "ic_court_decision_appeals_Housing_Staff", 
                                       "ic_court_decision_appeals_Housing_PAI", 
                                       "k_other_closure_methods_Housing_Staff", 
                                       "k_other_closure_methods_Housing_PAI", 
                                       "l_extensive_services_Housing_Staff", 
                                       "l_extensive_services_Housing_PAI",
                                       "cases_closed_limited_Housing", "a_counsel_and_advice_Housing", 
                                       "b_limited_action_Housing", "cases_closed_extended_Housing", 
                                       "f_negotiated_settlement_w_o_litigation_Housing", 
                                       "g_negotiated_settlement_w_litigation_Housing", 
                                       "h_agency_decision_Housing", "ia_court_decision_uncontested_Housing", 
                                       "ib_court_decision_contested_Housing", "ic_court_decision_appeals_Housing",
                                       "k_other_closure_methods_Housing", "l_extensive_services_Housing", 
                                       "cases_closed_contested_Housing"),
                         
                         "Income" = c("Income_Staff", "Income_PAI", "Total_Income", 
                                      "cases_closed_limited_Income_Staff", 
                                      "cases_closed_limited_Income_PAI", 
                                      "cases_closed_extended_Income_Staff", 
                                      "cases_closed_extended_Income_PAI", 
                                      "cases_closed_contested_Income_Staff", 
                                      "cases_closed_contested_Income_PAI", 
                                      "a_counsel_and_advice_Income_Staff", 
                                      "a_counsel_and_advice_Income_PAI", 
                                      "b_limited_action_Income_Staff", 
                                      "b_limited_action_Income_PAI", 
                                      "f_negotiated_settlement_w_o_litigation_Income_Staff", 
                                      "f_negotiated_settlement_w_o_litigation_Income_PAI", 
                                      "g_negotiated_settlement_w_litigation_Income_Staff", 
                                      "g_negotiated_settlement_w_litigation_Income_PAI", 
                                      "h_agency_decision_Income_Staff", 
                                      "h_agency_decision_Income_PAI", 
                                      "ia_court_decision_uncontested_Income_Staff", 
                                      "ia_court_decision_uncontested_Income_PAI", 
                                      "ib_court_decision_contested_Income_Staff", 
                                      "ib_court_decision_contested_Income_PAI", 
                                      "ic_court_decision_appeals_Income_Staff", 
                                      "ic_court_decision_appeals_Income_PAI", 
                                      "k_other_closure_methods_Income_Staff", 
                                      "k_other_closure_methods_Income_PAI", 
                                      "l_extensive_services_Income_Staff", 
                                      "l_extensive_services_Income_PAI",
                                      "cases_closed_limited_Income", "a_counsel_and_advice_Income", 
                                      "b_limited_action_Income", "cases_closed_extended_Income", 
                                      "f_negotiated_settlement_w_o_litigation_Income", 
                                      "g_negotiated_settlement_w_litigation_Income", 
                                      "h_agency_decision_Income", "ia_court_decision_uncontested_Income", 
                                      "ib_court_decision_contested_Income", "ic_court_decision_appeals_Income",
                                      "k_other_closure_methods_Income", "l_extensive_services_Income", 
                                      "cases_closed_contested_Income"),
                         
                         "Individual" = c("Individual_Staff", "Individual_PAI", "Total_Individual", 
                                          "cases_closed_limited_Individual_Staff", 
                                          "cases_closed_limited_Individual_PAI", 
                                          "cases_closed_extended_Individual_Staff", 
                                          "cases_closed_extended_Individual_PAI", 
                                          "cases_closed_contested_Individual_Staff", 
                                          "cases_closed_contested_Individual_PAI", 
                                          "a_counsel_and_advice_Individual_Staff", 
                                          "a_counsel_and_advice_Individual_PAI", 
                                          "b_limited_action_Individual_Staff", 
                                          "b_limited_action_Individual_PAI", 
                                          "f_negotiated_settlement_w_o_litigation_Individual_Staff", 
                                          "f_negotiated_settlement_w_o_litigation_Individual_PAI", 
                                          "g_negotiated_settlement_w_litigation_Individual_Staff", 
                                          "g_negotiated_settlement_w_litigation_Individual_PAI", 
                                          "h_agency_decision_Individual_Staff", 
                                          "h_agency_decision_Individual_PAI", 
                                          "ia_court_decision_uncontested_Individual_Staff", 
                                          "ia_court_decision_uncontested_Individual_PAI", 
                                          "ib_court_decision_contested_Individual_Staff", 
                                          "ib_court_decision_contested_Individual_PAI", 
                                          "ic_court_decision_appeals_Individual_Staff", 
                                          "ic_court_decision_appeals_Individual_PAI", 
                                          "k_other_closure_methods_Individual_Staff", 
                                          "k_other_closure_methods_Individual_PAI", 
                                          "l_extensive_services_Individual_Staff", 
                                          "l_extensive_services_Individual_PAI",
                                          "cases_closed_limited_Individual", "a_counsel_and_advice_Individual", 
                                          "b_limited_action_Individual", "cases_closed_extended_Individual", 
                                          "f_negotiated_settlement_w_o_litigation_Individual", 
                                          "g_negotiated_settlement_w_litigation_Individual", 
                                          "h_agency_decision_Individual", "ia_court_decision_uncontested_Individual", 
                                          "ib_court_decision_contested_Individual", "ic_court_decision_appeals_Individual",
                                          "k_other_closure_methods_Individual", "l_extensive_services_Individual", 
                                          "cases_closed_contested_Individual"),
                         
                         "Juvenile" = c("Juvenile_Staff", "Juvenile_PAI", "Total_Juvenile", 
                                        "cases_closed_limited_Juvenile_Staff", 
                                        "cases_closed_limited_Juvenile_PAI", 
                                        "cases_closed_extended_Juvenile_Staff", 
                                        "cases_closed_extended_Juvenile_PAI", 
                                        "cases_closed_contested_Juvenile_Staff", 
                                        "cases_closed_contested_Juvenile_PAI", 
                                        "a_counsel_and_advice_Juvenile_Staff", 
                                        "a_counsel_and_advice_Juvenile_PAI", 
                                        "b_limited_action_Juvenile_Staff", 
                                        "b_limited_action_Juvenile_PAI", 
                                        "f_negotiated_settlement_w_o_litigation_Juvenile_Staff", 
                                        "f_negotiated_settlement_w_o_litigation_Juvenile_PAI", 
                                        "g_negotiated_settlement_w_litigation_Juvenile_Staff", 
                                        "g_negotiated_settlement_w_litigation_Juvenile_PAI", 
                                        "h_agency_decision_Juvenile_Staff", 
                                        "h_agency_decision_Juvenile_PAI", 
                                        "ia_court_decision_uncontested_Juvenile_Staff", 
                                        "ia_court_decision_uncontested_Juvenile_PAI", 
                                        "ib_court_decision_contested_Juvenile_Staff", 
                                        "ib_court_decision_contested_Juvenile_PAI", 
                                        "ic_court_decision_appeals_Juvenile_Staff", 
                                        "ic_court_decision_appeals_Juvenile_PAI", 
                                        "k_other_closure_methods_Juvenile_Staff", 
                                        "k_other_closure_methods_Juvenile_PAI", 
                                        "l_extensive_services_Juvenile_Staff", 
                                        "l_extensive_services_Juvenile_PAI",
                                        "cases_closed_limited_Juvenile", "a_counsel_and_advice_Juvenile", 
                                        "b_limited_action_Juvenile", "cases_closed_extended_Juvenile", 
                                        "f_negotiated_settlement_w_o_litigation_Juvenile", 
                                        "g_negotiated_settlement_w_litigation_Juvenile", 
                                        "h_agency_decision_Juvenile", "ia_court_decision_uncontested_Juvenile", 
                                        "ib_court_decision_contested_Juvenile", "ic_court_decision_appeals_Juvenile",
                                        "k_other_closure_methods_Juvenile", "l_extensive_services_Juvenile", 
                                        "cases_closed_contested_Juvenile"),
                         
                         "Misc" = c("Misc_Staff", "Misc_PAI", "Total_Misc", 
                                    "cases_closed_limited_Misc_Staff", 
                                    "cases_closed_limited_Misc_PAI", 
                                    "cases_closed_extended_Misc_Staff", 
                                    "cases_closed_extended_Misc_PAI", 
                                    "cases_closed_contested_Misc_Staff", 
                                    "cases_closed_contested_Misc_PAI", 
                                    "a_counsel_and_advice_Misc_Staff", 
                                    "a_counsel_and_advice_Misc_PAI", 
                                    "b_limited_action_Misc_Staff", 
                                    "b_limited_action_Misc_PAI", 
                                    "f_negotiated_settlement_w_o_litigation_Misc_Staff", 
                                    "f_negotiated_settlement_w_o_litigation_Misc_PAI", 
                                    "g_negotiated_settlement_w_litigation_Misc_Staff", 
                                    "g_negotiated_settlement_w_litigation_Misc_PAI", 
                                    "h_agency_decision_Misc_Staff", 
                                    "h_agency_decision_Misc_PAI", 
                                    "ia_court_decision_uncontested_Misc_Staff", 
                                    "ia_court_decision_uncontested_Misc_PAI", 
                                    "ib_court_decision_contested_Misc_Staff", 
                                    "ib_court_decision_contested_Misc_PAI", 
                                    "ic_court_decision_appeals_Misc_Staff", 
                                    "ic_court_decision_appeals_Misc_PAI", 
                                    "k_other_closure_methods_Misc_Staff", 
                                    "k_other_closure_methods_Misc_PAI", 
                                    "l_extensive_services_Misc_Staff", 
                                    "l_extensive_services_Misc_PAI",
                                    "cases_closed_limited_Misc", "a_counsel_and_advice_Misc", 
                                    "b_limited_action_Misc", "cases_closed_extended_Misc", 
                                    "f_negotiated_settlement_w_o_litigation_Misc", 
                                    "g_negotiated_settlement_w_litigation_Misc", 
                                    "h_agency_decision_Misc", "ia_court_decision_uncontested_Misc", 
                                    "ib_court_decision_contested_Misc", "ic_court_decision_appeals_Misc",
                                    "k_other_closure_methods_Misc", "l_extensive_services_Misc", 
                                    "cases_closed_contested_Misc"))

List_PAI_cat <- list("Total" = c("Total_Consumer", "Total_Education", "Total_Employment", "Total_Family", 
                                 "Total_Health", "Total_Housing", "Total_Income", "Total_Individual", 
                                 "Total_Juvenile", "Total_Misc", "Total_a_counsel_and_advice", 
                                 "Total_b_limited_action", "Total_f_negotiated_settlement_w_o_litigation", 
                                 "Total_g_negotiated_settlement_w_litigation", "Total_h_agency_decision", 
                                 "Total_ia_court_decision_uncontested", "Total_ib_court_decision_contested", 
                                 "Total_ic_court_decision_appeals", "Total_k_other_closure_methods", 
                                 "Total_l_extensive_services", "cases_closed_limited_Consumer", 
                                 "cases_closed_limited_Education", "cases_closed_limited_Employment", 
                                 "cases_closed_limited_Family", "cases_closed_limited_Health", 
                                 "cases_closed_limited_Housing", "cases_closed_limited_Income", 
                                 "cases_closed_limited_Individual", "cases_closed_limited_Juvenile", 
                                 "cases_closed_limited_Misc", "a_counsel_and_advice_Consumer", 
                                 "a_counsel_and_advice_Education", "a_counsel_and_advice_Employment", 
                                 "a_counsel_and_advice_Family", "a_counsel_and_advice_Health", 
                                 "a_counsel_and_advice_Housing", "a_counsel_and_advice_Income", 
                                 "a_counsel_and_advice_Individual", "a_counsel_and_advice_Juvenile", 
                                 "a_counsel_and_advice_Misc", "b_limited_action_Consumer", 
                                 "b_limited_action_Education", "b_limited_action_Employment", 
                                 "b_limited_action_Family", "b_limited_action_Health", 
                                 "b_limited_action_Housing", "b_limited_action_Income", 
                                 "b_limited_action_Individual", "b_limited_action_Juvenile", 
                                 "b_limited_action_Misc", "cases_closed_extended_Consumer", 
                                 "cases_closed_extended_Education", "cases_closed_extended_Employment", 
                                 "cases_closed_extended_Family", "cases_closed_extended_Health", 
                                 "cases_closed_extended_Housing", "cases_closed_extended_Income", 
                                 "cases_closed_extended_Individual", "cases_closed_extended_Juvenile", 
                                 "cases_closed_extended_Misc", 
                                 "f_negotiated_settlement_w_o_litigation_Consumer", 
                                 "f_negotiated_settlement_w_o_litigation_Education", 
                                 "f_negotiated_settlement_w_o_litigation_Employment", 
                                 "f_negotiated_settlement_w_o_litigation_Family", 
                                 "f_negotiated_settlement_w_o_litigation_Health", 
                                 "f_negotiated_settlement_w_o_litigation_Housing", 
                                 "f_negotiated_settlement_w_o_litigation_Income", 
                                 "f_negotiated_settlement_w_o_litigation_Individual", 
                                 "f_negotiated_settlement_w_o_litigation_Juvenile", 
                                 "f_negotiated_settlement_w_o_litigation_Misc", 
                                 "g_negotiated_settlement_w_litigation_Consumer", 
                                 "g_negotiated_settlement_w_litigation_Education", 
                                 "g_negotiated_settlement_w_litigation_Employment", 
                                 "g_negotiated_settlement_w_litigation_Family", 
                                 "g_negotiated_settlement_w_litigation_Health", 
                                 "g_negotiated_settlement_w_litigation_Housing", 
                                 "g_negotiated_settlement_w_litigation_Income", 
                                 "g_negotiated_settlement_w_litigation_Individual", 
                                 "g_negotiated_settlement_w_litigation_Juvenile", 
                                 "g_negotiated_settlement_w_litigation_Misc", 
                                 "h_agency_decision_Consumer", "h_agency_decision_Education", 
                                 "h_agency_decision_Employment", "h_agency_decision_Family", 
                                 "h_agency_decision_Health", "h_agency_decision_Housing", 
                                 "h_agency_decision_Income", "h_agency_decision_Individual", 
                                 "h_agency_decision_Juvenile", "h_agency_decision_Misc", 
                                 "ia_court_decision_uncontested_Consumer", 
                                 "ia_court_decision_uncontested_Education", 
                                 "ia_court_decision_uncontested_Employment", 
                                 "ia_court_decision_uncontested_Family", 
                                 "ia_court_decision_uncontested_Health", 
                                 "ia_court_decision_uncontested_Housing", 
                                 "ia_court_decision_uncontested_Income", 
                                 "ia_court_decision_uncontested_Individual", 
                                 "ia_court_decision_uncontested_Juvenile", 
                                 "ia_court_decision_uncontested_Misc", 
                                 "ib_court_decision_contested_Consumer", 
                                 "ib_court_decision_contested_Education", 
                                 "ib_court_decision_contested_Employment", 
                                 "ib_court_decision_contested_Family", 
                                 "ib_court_decision_contested_Health", 
                                 "ib_court_decision_contested_Housing", 
                                 "ib_court_decision_contested_Income", 
                                 "ib_court_decision_contested_Individual", 
                                 "ib_court_decision_contested_Juvenile", 
                                 "ib_court_decision_contested_Misc", "ic_court_decision_appeals_Consumer", 
                                 "ic_court_decision_appeals_Education", 
                                 "ic_court_decision_appeals_Employment", 
                                 "ic_court_decision_appeals_Family", "ic_court_decision_appeals_Health", 
                                 "ic_court_decision_appeals_Housing", "ic_court_decision_appeals_Income", 
                                 "ic_court_decision_appeals_Individual", 
                                 "ic_court_decision_appeals_Juvenile", "ic_court_decision_appeals_Misc", 
                                 "k_other_closure_methods_Consumer", "k_other_closure_methods_Education", 
                                 "k_other_closure_methods_Employment", "k_other_closure_methods_Family", 
                                 "k_other_closure_methods_Health", "k_other_closure_methods_Housing", 
                                 "k_other_closure_methods_Income", "k_other_closure_methods_Individual", 
                                 "k_other_closure_methods_Juvenile", "k_other_closure_methods_Misc", 
                                 "l_extensive_services_Consumer", "l_extensive_services_Education", 
                                 "l_extensive_services_Employment", "l_extensive_services_Family", 
                                 "l_extensive_services_Health", "l_extensive_services_Housing", 
                                 "l_extensive_services_Income", "l_extensive_services_Individual", 
                                 "l_extensive_services_Juvenile", "l_extensive_services_Misc", 
                                 "cases_closed_contested_Consumer", "cases_closed_contested_Education", 
                                 "cases_closed_contested_Employment", "cases_closed_contested_Family", 
                                 "cases_closed_contested_Health", "cases_closed_contested_Housing", 
                                 "cases_closed_contested_Income", "cases_closed_contested_Individual", 
                                 "cases_closed_contested_Juvenile", "cases_closed_contested_Misc"),
                     
                     "PAI" = c("Consumer_PAI", "Education_PAI", "Employment_PAI", "Family_PAI", 
                               "Health_PAI", "Housing_PAI", "Income_PAI", "Individual_PAI", 
                               "Juvenile_PAI", "Misc_PAI", "Total_PAI", "cases_closed_limited_Consumer_PAI",
                               "cases_closed_limited_Education_PAI", "cases_closed_limited_Employment_PAI",
                               "cases_closed_limited_Family_PAI", "cases_closed_limited_Health_PAI", 
                               "cases_closed_limited_Housing_PAI", "cases_closed_limited_Income_PAI", 
                               "cases_closed_limited_Individual_PAI", "cases_closed_limited_Juvenile_PAI", 
                               "cases_closed_limited_Misc_PAI", "cases_closed_extended_Consumer_PAI", 
                               "cases_closed_extended_Education_PAI", "cases_closed_extended_Employment_PAI", 
                               "cases_closed_extended_Family_PAI", "cases_closed_extended_Health_PAI", 
                               "cases_closed_extended_Housing_PAI", "cases_closed_extended_Income_PAI", 
                               "cases_closed_extended_Individual_PAI", "cases_closed_extended_Juvenile_PAI", 
                               "cases_closed_extended_Misc_PAI", "cases_closed_contested_Consumer_PAI", 
                               "cases_closed_contested_Education_PAI", "cases_closed_contested_Employment_PAI", 
                               "cases_closed_contested_Family_PAI", "cases_closed_contested_Health_PAI", 
                               "cases_closed_contested_Housing_PAI", "cases_closed_contested_Income_PAI", 
                               "cases_closed_contested_Individual_PAI", "cases_closed_contested_Juvenile_PAI", 
                               "cases_closed_contested_Misc_PAI", "a_counsel_and_advice_Consumer_PAI", 
                               "a_counsel_and_advice_Education_PAI", "a_counsel_and_advice_Employment_PAI", 
                               "a_counsel_and_advice_Family_PAI", "a_counsel_and_advice_Health_PAI", 
                               "a_counsel_and_advice_Housing_PAI", "a_counsel_and_advice_Income_PAI", 
                               "a_counsel_and_advice_Individual_PAI", "a_counsel_and_advice_Juvenile_PAI", 
                               "a_counsel_and_advice_Misc_PAI", "b_limited_action_Consumer_PAI", 
                               "b_limited_action_Education_PAI", "b_limited_action_Employment_PAI", 
                               "b_limited_action_Family_PAI", "b_limited_action_Health_PAI", 
                               "b_limited_action_Housing_PAI", "b_limited_action_Income_PAI", 
                               "b_limited_action_Individual_PAI", "b_limited_action_Juvenile_PAI", 
                               "b_limited_action_Misc_PAI", "f_negotiated_settlement_w_o_litigation_Consumer_PAI", 
                               "f_negotiated_settlement_w_o_litigation_Education_PAI", 
                               "f_negotiated_settlement_w_o_litigation_Employment_PAI", 
                               "f_negotiated_settlement_w_o_litigation_Family_PAI", 
                               "f_negotiated_settlement_w_o_litigation_Health_PAI", 
                               "f_negotiated_settlement_w_o_litigation_Housing_PAI", 
                               "f_negotiated_settlement_w_o_litigation_Income_PAI", 
                               "f_negotiated_settlement_w_o_litigation_Individual_PAI", 
                               "f_negotiated_settlement_w_o_litigation_Juvenile_PAI", 
                               "f_negotiated_settlement_w_o_litigation_Misc_PAI", 
                               "g_negotiated_settlement_w_litigation_Consumer_PAI", 
                               "g_negotiated_settlement_w_litigation_Education_PAI", 
                               "g_negotiated_settlement_w_litigation_Employment_PAI", 
                               "g_negotiated_settlement_w_litigation_Family_PAI", 
                               "g_negotiated_settlement_w_litigation_Health_PAI", 
                               "g_negotiated_settlement_w_litigation_Housing_PAI", 
                               "g_negotiated_settlement_w_litigation_Income_PAI", 
                               "g_negotiated_settlement_w_litigation_Individual_PAI", 
                               "g_negotiated_settlement_w_litigation_Juvenile_PAI", 
                               "g_negotiated_settlement_w_litigation_Misc_PAI", 
                               "h_agency_decision_Consumer_PAI", "h_agency_decision_Education_PAI", 
                               "h_agency_decision_Employment_PAI", "h_agency_decision_Family_PAI", 
                               "h_agency_decision_Health_PAI", "h_agency_decision_Housing_PAI", 
                               "h_agency_decision_Income_PAI", "h_agency_decision_Individual_PAI", 
                               "h_agency_decision_Juvenile_PAI", "h_agency_decision_Misc_PAI", 
                               "ia_court_decision_uncontested_Consumer_PAI", 
                               "ia_court_decision_uncontested_Education_PAI", 
                               "ia_court_decision_uncontested_Employment_PAI", 
                               "ia_court_decision_uncontested_Family_PAI", 
                               "ia_court_decision_uncontested_Health_PAI", 
                               "ia_court_decision_uncontested_Housing_PAI", 
                               "ia_court_decision_uncontested_Income_PAI", 
                               "ia_court_decision_uncontested_Individual_PAI", 
                               "ia_court_decision_uncontested_Juvenile_PAI", 
                               "ia_court_decision_uncontested_Misc_PAI", 
                               "ib_court_decision_contested_Consumer_PAI", 
                               "ib_court_decision_contested_Education_PAI", 
                               "ib_court_decision_contested_Employment_PAI", 
                               "ib_court_decision_contested_Family_PAI", 
                               "ib_court_decision_contested_Health_PAI", 
                               "ib_court_decision_contested_Housing_PAI", 
                               "ib_court_decision_contested_Income_PAI", 
                               "ib_court_decision_contested_Individual_PAI", 
                               "ib_court_decision_contested_Juvenile_PAI", 
                               "ib_court_decision_contested_Misc_PAI", 
                               "ic_court_decision_appeals_Consumer_PAI", 
                               "ic_court_decision_appeals_Education_PAI", 
                               "ic_court_decision_appeals_Employment_PAI", 
                               "ic_court_decision_appeals_Family_PAI", 
                               "ic_court_decision_appeals_Health_PAI", 
                               "ic_court_decision_appeals_Housing_PAI", 
                               "ic_court_decision_appeals_Income_PAI", 
                               "ic_court_decision_appeals_Individual_PAI", 
                               "ic_court_decision_appeals_Juvenile_PAI", 
                               "ic_court_decision_appeals_Misc_PAI", 
                               "k_other_closure_methods_Consumer_PAI", 
                               "k_other_closure_methods_Education_PAI", 
                               "k_other_closure_methods_Employment_PAI", 
                               "k_other_closure_methods_Family_PAI",
                               "k_other_closure_methods_Health_PAI", 
                               "k_other_closure_methods_Housing_PAI", 
                               "k_other_closure_methods_Income_PAI", 
                               "k_other_closure_methods_Individual_PAI", 
                               "k_other_closure_methods_Juvenile_PAI", 
                               "k_other_closure_methods_Misc_PAI", 
                               "l_extensive_services_Consumer_PAI", 
                               "l_extensive_services_Education_PAI", 
                               "l_extensive_services_Employment_PAI", 
                               "l_extensive_services_Family_PAI", 
                               "l_extensive_services_Health_PAI", 
                               "l_extensive_services_Housing_PAI", 
                               "l_extensive_services_Income_PAI", 
                               "l_extensive_services_Individual_PAI", 
                               "l_extensive_services_Juvenile_PAI", "l_extensive_services_Misc_PAI"),
                     
                     "Staff" = c("Consumer_Staff", "Education_Staff", "Employment_Staff", "Family_Staff", 
                                 "Health_Staff", "Housing_Staff", "Income_Staff", "Individual_Staff", 
                                 "Juvenile_Staff", "Misc_Staff", "Total_Staff", "cases_closed_limited_Consumer_Staff",
                                 "cases_closed_limited_Education_Staff", "cases_closed_limited_Employment_Staff",
                                 "cases_closed_limited_Family_Staff", "cases_closed_limited_Health_Staff", 
                                 "cases_closed_limited_Housing_Staff", "cases_closed_limited_Income_Staff", 
                                 "cases_closed_limited_Individual_Staff", "cases_closed_limited_Juvenile_Staff", 
                                 "cases_closed_limited_Misc_Staff", "cases_closed_extended_Consumer_Staff", 
                                 "cases_closed_extended_Education_Staff", "cases_closed_extended_Employment_Staff", 
                                 "cases_closed_extended_Family_Staff", "cases_closed_extended_Health_Staff", 
                                 "cases_closed_extended_Housing_Staff", "cases_closed_extended_Income_Staff", 
                                 "cases_closed_extended_Individual_Staff", "cases_closed_extended_Juvenile_Staff", 
                                 "cases_closed_extended_Misc_Staff", "cases_closed_contested_Consumer_Staff", 
                                 "cases_closed_contested_Education_Staff", "cases_closed_contested_Employment_Staff", 
                                 "cases_closed_contested_Family_Staff", "cases_closed_contested_Health_Staff", 
                                 "cases_closed_contested_Housing_Staff", "cases_closed_contested_Income_Staff", 
                                 "cases_closed_contested_Individual_Staff", "cases_closed_contested_Juvenile_Staff", 
                                 "cases_closed_contested_Misc_Staff", "a_counsel_and_advice_Consumer_Staff", 
                                 "a_counsel_and_advice_Education_Staff", "a_counsel_and_advice_Employment_Staff", 
                                 "a_counsel_and_advice_Family_Staff", "a_counsel_and_advice_Health_Staff", 
                                 "a_counsel_and_advice_Housing_Staff", "a_counsel_and_advice_Income_Staff", 
                                 "a_counsel_and_advice_Individual_Staff", "a_counsel_and_advice_Juvenile_Staff", 
                                 "a_counsel_and_advice_Misc_Staff", "b_limited_action_Consumer_Staff", 
                                 "b_limited_action_Education_Staff", "b_limited_action_Employment_Staff", 
                                 "b_limited_action_Family_Staff", "b_limited_action_Health_Staff", 
                                 "b_limited_action_Housing_Staff", "b_limited_action_Income_Staff", 
                                 "b_limited_action_Individual_Staff", "b_limited_action_Juvenile_Staff", 
                                 "b_limited_action_Misc_Staff", "f_negotiated_settlement_w_o_litigation_Consumer_Staff", 
                                 "f_negotiated_settlement_w_o_litigation_Education_Staff", 
                                 "f_negotiated_settlement_w_o_litigation_Employment_Staff", 
                                 "f_negotiated_settlement_w_o_litigation_Family_Staff", 
                                 "f_negotiated_settlement_w_o_litigation_Health_Staff", 
                                 "f_negotiated_settlement_w_o_litigation_Housing_Staff", 
                                 "f_negotiated_settlement_w_o_litigation_Income_Staff", 
                                 "f_negotiated_settlement_w_o_litigation_Individual_Staff", 
                                 "f_negotiated_settlement_w_o_litigation_Juvenile_Staff", 
                                 "f_negotiated_settlement_w_o_litigation_Misc_Staff", 
                                 "g_negotiated_settlement_w_litigation_Consumer_Staff", 
                                 "g_negotiated_settlement_w_litigation_Education_Staff", 
                                 "g_negotiated_settlement_w_litigation_Employment_Staff", 
                                 "g_negotiated_settlement_w_litigation_Family_Staff", 
                                 "g_negotiated_settlement_w_litigation_Health_Staff", 
                                 "g_negotiated_settlement_w_litigation_Housing_Staff", 
                                 "g_negotiated_settlement_w_litigation_Income_Staff", 
                                 "g_negotiated_settlement_w_litigation_Individual_Staff", 
                                 "g_negotiated_settlement_w_litigation_Juvenile_Staff", 
                                 "g_negotiated_settlement_w_litigation_Misc_Staff", 
                                 "h_agency_decision_Consumer_Staff", "h_agency_decision_Education_Staff", 
                                 "h_agency_decision_Employment_Staff", "h_agency_decision_Family_Staff", 
                                 "h_agency_decision_Health_Staff", "h_agency_decision_Housing_Staff", 
                                 "h_agency_decision_Income_Staff", "h_agency_decision_Individual_Staff", 
                                 "h_agency_decision_Juvenile_Staff", "h_agency_decision_Misc_Staff", 
                                 "ia_court_decision_uncontested_Consumer_Staff", 
                                 "ia_court_decision_uncontested_Education_Staff", 
                                 "ia_court_decision_uncontested_Employment_Staff", 
                                 "ia_court_decision_uncontested_Family_Staff", 
                                 "ia_court_decision_uncontested_Health_Staff", 
                                 "ia_court_decision_uncontested_Housing_Staff", 
                                 "ia_court_decision_uncontested_Income_Staff", 
                                 "ia_court_decision_uncontested_Individual_Staff", 
                                 "ia_court_decision_uncontested_Juvenile_Staff", 
                                 "ia_court_decision_uncontested_Misc_Staff", 
                                 "ib_court_decision_contested_Consumer_Staff", 
                                 "ib_court_decision_contested_Education_Staff", 
                                 "ib_court_decision_contested_Employment_Staff", 
                                 "ib_court_decision_contested_Family_Staff", 
                                 "ib_court_decision_contested_Health_Staff", 
                                 "ib_court_decision_contested_Housing_Staff", 
                                 "ib_court_decision_contested_Income_Staff", 
                                 "ib_court_decision_contested_Individual_Staff", 
                                 "ib_court_decision_contested_Juvenile_Staff", 
                                 "ib_court_decision_contested_Misc_Staff", 
                                 "ic_court_decision_appeals_Consumer_Staff", 
                                 "ic_court_decision_appeals_Education_Staff", 
                                 "ic_court_decision_appeals_Employment_Staff", 
                                 "ic_court_decision_appeals_Family_Staff", 
                                 "ic_court_decision_appeals_Health_Staff", 
                                 "ic_court_decision_appeals_Housing_Staff", 
                                 "ic_court_decision_appeals_Income_Staff", 
                                 "ic_court_decision_appeals_Individual_Staff", 
                                 "ic_court_decision_appeals_Juvenile_Staff", 
                                 "ic_court_decision_appeals_Misc_Staff", 
                                 "k_other_closure_methods_Consumer_Staff", 
                                 "k_other_closure_methods_Education_Staff", 
                                 "k_other_closure_methods_Employment_Staff", 
                                 "k_other_closure_methods_Family_Staff",
                                 "k_other_closure_methods_Health_Staff", 
                                 "k_other_closure_methods_Housing_Staff", 
                                 "k_other_closure_methods_Income_Staff", 
                                 "k_other_closure_methods_Individual_Staff", 
                                 "k_other_closure_methods_Juvenile_Staff", 
                                 "k_other_closure_methods_Misc_Staff", 
                                 "l_extensive_services_Consumer_Staff", 
                                 "l_extensive_services_Education_Staff", 
                                 "l_extensive_services_Employment_Staff", 
                                 "l_extensive_services_Family_Staff", 
                                 "l_extensive_services_Health_Staff", 
                                 "l_extensive_services_Housing_Staff", 
                                 "l_extensive_services_Income_Staff", 
                                 "l_extensive_services_Individual_Staff", 
                                 "l_extensive_services_Juvenile_Staff", "l_extensive_services_Misc_Staff"))

List_subcat <- list("Total Limited" = c("cases_closed_limited_Consumer_Staff", "cases_closed_limited_Consumer_PAI", 
                                        "cases_closed_limited_Education_Staff", "cases_closed_limited_Education_PAI",
                                        "cases_closed_limited_Employment_Staff", "cases_closed_limited_Employment_PAI",
                                        "cases_closed_limited_Family_Staff", "cases_closed_limited_Family_PAI", 
                                        "cases_closed_limited_Health_Staff", "cases_closed_limited_Health_PAI", 
                                        "cases_closed_limited_Housing_Staff", "cases_closed_limited_Housing_PAI", 
                                        "cases_closed_limited_Income_Staff", "cases_closed_limited_Income_PAI", 
                                        "cases_closed_limited_Individual_Staff", "cases_closed_limited_Individual_PAI", 
                                        "cases_closed_limited_Juvenile_Staff", "cases_closed_limited_Juvenile_PAI",
                                        "cases_closed_limited_Misc_Staff", "cases_closed_limited_Misc_PAI", 
                                        "cases_closed_limited_Consumer", "cases_closed_limited_Education", 
                                        "cases_closed_limited_Employment", "cases_closed_limited_Family", 
                                        "cases_closed_limited_Health", "cases_closed_limited_Housing", 
                                        "cases_closed_limited_Income", "cases_closed_limited_Individual", 
                                        "cases_closed_limited_Juvenile", "cases_closed_limited_Misc"),

                    "Counsel and Advice" = c("a_counsel_and_advice_Consumer_Staff", 
                                               "a_counsel_and_advice_Consumer_PAI", 
                                               "a_counsel_and_advice_Education_Staff", 
                                               "a_counsel_and_advice_Education_PAI", 
                                               "a_counsel_and_advice_Employment_Staff", 
                                               "a_counsel_and_advice_Employment_PAI", 
                                               "a_counsel_and_advice_Family_Staff", 
                                               "a_counsel_and_advice_Family_PAI", 
                                               "a_counsel_and_advice_Health_Staff", 
                                               "a_counsel_and_advice_Health_PAI", 
                                               "a_counsel_and_advice_Housing_Staff", 
                                               "a_counsel_and_advice_Housing_PAI", 
                                               "a_counsel_and_advice_Income_Staff", 
                                               "a_counsel_and_advice_Income_PAI", 
                                               "a_counsel_and_advice_Individual_Staff", 
                                               "a_counsel_and_advice_Individual_PAI", 
                                               "a_counsel_and_advice_Juvenile_Staff", 
                                               "a_counsel_and_advice_Juvenile_PAI", 
                                               "a_counsel_and_advice_Misc_Staff", 
                                               "a_counsel_and_advice_Misc_PAI", 
                                               "Total_a_counsel_and_advice",
                                               "a_counsel_and_advice_Consumer", 
                                               "a_counsel_and_advice_Education", 
                                               "a_counsel_and_advice_Employment", 
                                               "a_counsel_and_advice_Family", 
                                               "a_counsel_and_advice_Health", 
                                               "a_counsel_and_advice_Housing", 
                                               "a_counsel_and_advice_Income", 
                                               "a_counsel_and_advice_Individual", 
                                               "a_counsel_and_advice_Juvenile", 
                                               "a_counsel_and_advice_Misc"),
                    
                    "Limited Action" = c("b_limited_action_Consumer_Staff", 
                                           "b_limited_action_Consumer_PAI", 
                                           "b_limited_action_Education_Staff", 
                                           "b_limited_action_Education_PAI", 
                                           "b_limited_action_Employment_Staff", 
                                           "b_limited_action_Employment_PAI", 
                                           "b_limited_action_Family_Staff", 
                                           "b_limited_action_Family_PAI", 
                                           "b_limited_action_Health_Staff", 
                                           "b_limited_action_Health_PAI", 
                                           "b_limited_action_Housing_Staff", 
                                           "b_limited_action_Housing_PAI", 
                                           "b_limited_action_Income_Staff", 
                                           "b_limited_action_Income_PAI", 
                                           "b_limited_action_Individual_Staff", 
                                           "b_limited_action_Individual_PAI", 
                                           "b_limited_action_Juvenile_Staff", 
                                           "b_limited_action_Juvenile_PAI", 
                                           "b_limited_action_Misc_Staff", 
                                           "b_limited_action_Misc_PAI", 
                                           "Total_b_limited_action",
                                           "b_limited_action_Consumer", "b_limited_action_Education", 
                                           "b_limited_action_Employment", "b_limited_action_Family", 
                                           "b_limited_action_Health", "b_limited_action_Housing", 
                                           "b_limited_action_Income", "b_limited_action_Individual", 
                                           "b_limited_action_Juvenile", "b_limited_action_Misc"),
                    
                    "Total Extended" = c("cases_closed_extended_Consumer_Staff", "cases_closed_extended_Consumer_PAI", 
                                        "cases_closed_extended_Education_Staff", "cases_closed_extended_Education_PAI",
                                        "cases_closed_extended_Employment_Staff", "cases_closed_extended_Employment_PAI",
                                        "cases_closed_extended_Family_Staff", "cases_closed_extended_Family_PAI",
                                        "cases_closed_extended_Health_Staff", "cases_closed_extended_Health_PAI",
                                        "cases_closed_extended_Housing_Staff", "cases_closed_extended_Housing_PAI",
                                        "cases_closed_extended_Income_Staff", "cases_closed_extended_Income_PAI", 
                                        "cases_closed_extended_Individual_Staff", "cases_closed_extended_Individual_PAI",
                                        "cases_closed_extended_Juvenile_Staff", "cases_closed_extended_Juvenile_PAI",
                                        "cases_closed_extended_Misc_Staff", "cases_closed_extended_Misc_PAI",
                                        "cases_closed_extended_Consumer", "cases_closed_extended_Education",
                                        "cases_closed_extended_Employment", "cases_closed_extended_Family",                                       
                                        "cases_closed_extended_Health", "cases_closed_extended_Housing", 
                                        "cases_closed_extended_Income", "cases_closed_extended_Individual", 
                                        "cases_closed_extended_Juvenile", "cases_closed_extended_Misc"),
                    
                    "Negotiated Settlement without Litigation" = 
                      c("f_negotiated_settlement_w_o_litigation_Consumer_Staff", 
                        "f_negotiated_settlement_w_o_litigation_Consumer_PAI", 
                        "f_negotiated_settlement_w_o_litigation_Education_Staff", 
                        "f_negotiated_settlement_w_o_litigation_Education_PAI", 
                        "f_negotiated_settlement_w_o_litigation_Employment_Staff", 
                        "f_negotiated_settlement_w_o_litigation_Employment_PAI", 
                        "f_negotiated_settlement_w_o_litigation_Family_Staff", 
                        "f_negotiated_settlement_w_o_litigation_Family_PAI", 
                        "f_negotiated_settlement_w_o_litigation_Health_Staff", 
                        "f_negotiated_settlement_w_o_litigation_Health_PAI", 
                        "f_negotiated_settlement_w_o_litigation_Housing_Staff", 
                        "f_negotiated_settlement_w_o_litigation_Housing_PAI", 
                        "f_negotiated_settlement_w_o_litigation_Income_Staff", 
                        "f_negotiated_settlement_w_o_litigation_Income_PAI", 
                        "f_negotiated_settlement_w_o_litigation_Individual_Staff", 
                        "f_negotiated_settlement_w_o_litigation_Individual_PAI", 
                        "f_negotiated_settlement_w_o_litigation_Juvenile_Staff", 
                        "f_negotiated_settlement_w_o_litigation_Juvenile_PAI", 
                        "f_negotiated_settlement_w_o_litigation_Misc_Staff", 
                        "f_negotiated_settlement_w_o_litigation_Misc_PAI", 
                        "Total_f_negotiated_settlement_w_o_litigation",
                        "f_negotiated_settlement_w_o_litigation_Consumer", 
                        "f_negotiated_settlement_w_o_litigation_Education", 
                        "f_negotiated_settlement_w_o_litigation_Employment", 
                        "f_negotiated_settlement_w_o_litigation_Family", 
                        "f_negotiated_settlement_w_o_litigation_Health", 
                        "f_negotiated_settlement_w_o_litigation_Housing", 
                        "f_negotiated_settlement_w_o_litigation_Income", 
                        "f_negotiated_settlement_w_o_litigation_Individual", 
                        "f_negotiated_settlement_w_o_litigation_Juvenile", 
                        "f_negotiated_settlement_w_o_litigation_Misc"),
                    
                    "Negotiated Settlement with Litigation" = 
                      c("g_negotiated_settlement_w_litigation_Consumer_Staff", 
                        "g_negotiated_settlement_w_litigation_Consumer_PAI", 
                        "g_negotiated_settlement_w_litigation_Education_Staff", 
                        "g_negotiated_settlement_w_litigation_Education_PAI", 
                        "g_negotiated_settlement_w_litigation_Employment_Staff", 
                        "g_negotiated_settlement_w_litigation_Employment_PAI", 
                        "g_negotiated_settlement_w_litigation_Family_Staff", 
                        "g_negotiated_settlement_w_litigation_Family_PAI", 
                        "g_negotiated_settlement_w_litigation_Health_Staff", 
                        "g_negotiated_settlement_w_litigation_Health_PAI", 
                        "g_negotiated_settlement_w_litigation_Housing_Staff", 
                        "g_negotiated_settlement_w_litigation_Housing_PAI", 
                        "g_negotiated_settlement_w_litigation_Income_Staff", 
                        "g_negotiated_settlement_w_litigation_Income_PAI", 
                        "g_negotiated_settlement_w_litigation_Individual_Staff", 
                        "g_negotiated_settlement_w_litigation_Individual_PAI", 
                        "g_negotiated_settlement_w_litigation_Juvenile_Staff", 
                        "g_negotiated_settlement_w_litigation_Juvenile_PAI", 
                        "g_negotiated_settlement_w_litigation_Misc_Staff", 
                        "g_negotiated_settlement_w_litigation_Misc_PAI", 
                        "Total_g_negotiated_settlement_w_litigation",
                        "g_negotiated_settlement_w_litigation_Consumer", 
                        "g_negotiated_settlement_w_litigation_Education", 
                        "g_negotiated_settlement_w_litigation_Employment", 
                        "g_negotiated_settlement_w_litigation_Family", 
                        "g_negotiated_settlement_w_litigation_Health", 
                        "g_negotiated_settlement_w_litigation_Housing", 
                        "g_negotiated_settlement_w_litigation_Income", 
                        "g_negotiated_settlement_w_litigation_Individual", 
                        "g_negotiated_settlement_w_litigation_Juvenile", 
                        "g_negotiated_settlement_w_litigation_Misc"),
                    
                    "Agency Decision" = c("h_agency_decision_Consumer_Staff", 
                                            "h_agency_decision_Consumer_PAI", "h_agency_decision_Education_Staff", 
                                            "h_agency_decision_Education_PAI", "h_agency_decision_Employment_Staff", 
                                            "h_agency_decision_Employment_PAI", "h_agency_decision_Family_Staff", 
                                            "h_agency_decision_Family_PAI", "h_agency_decision_Health_Staff", 
                                            "h_agency_decision_Health_PAI", "h_agency_decision_Housing_Staff", 
                                            "h_agency_decision_Housing_PAI", "h_agency_decision_Income_Staff", 
                                            "h_agency_decision_Income_PAI", "h_agency_decision_Individual_Staff", 
                                            "h_agency_decision_Individual_PAI", "h_agency_decision_Juvenile_Staff", 
                                            "h_agency_decision_Juvenile_PAI", "h_agency_decision_Misc_Staff", 
                                            "h_agency_decision_Misc_PAI", "Total_h_agency_decision",
                                            "h_agency_decision_Consumer", "h_agency_decision_Education", 
                                            "h_agency_decision_Employment", "h_agency_decision_Family", 
                                            "h_agency_decision_Health", "h_agency_decision_Housing", 
                                            "h_agency_decision_Income", "h_agency_decision_Individual", 
                                            "h_agency_decision_Juvenile", "h_agency_decision_Misc"),
                    
                    "Court Decision - Uncontested" = 
                      c("ia_court_decision_uncontested_Consumer_Staff", 
                        "ia_court_decision_uncontested_Consumer_PAI", 
                        "ia_court_decision_uncontested_Education_Staff", 
                        "ia_court_decision_uncontested_Education_PAI", 
                        "ia_court_decision_uncontested_Employment_Staff", 
                        "ia_court_decision_uncontested_Employment_PAI", 
                        "ia_court_decision_uncontested_Family_Staff", 
                        "ia_court_decision_uncontested_Family_PAI", 
                        "ia_court_decision_uncontested_Health_Staff", 
                        "ia_court_decision_uncontested_Health_PAI", 
                        "ia_court_decision_uncontested_Housing_Staff", 
                        "ia_court_decision_uncontested_Housing_PAI", 
                        "ia_court_decision_uncontested_Income_Staff", 
                        "ia_court_decision_uncontested_Income_PAI", 
                        "ia_court_decision_uncontested_Individual_Staff", 
                        "ia_court_decision_uncontested_Individual_PAI", 
                        "ia_court_decision_uncontested_Juvenile_Staff", 
                        "ia_court_decision_uncontested_Juvenile_PAI", 
                        "ia_court_decision_uncontested_Misc_Staff", 
                        "ia_court_decision_uncontested_Misc_PAI", 
                        "Total_ia_court_decision_uncontested",
                        "ia_court_decision_uncontested_Consumer", 
                        "ia_court_decision_uncontested_Education", 
                        "ia_court_decision_uncontested_Employment", 
                        "ia_court_decision_uncontested_Family", 
                        "ia_court_decision_uncontested_Health", 
                        "ia_court_decision_uncontested_Housing", 
                        "ia_court_decision_uncontested_Income", 
                        "ia_court_decision_uncontested_Individual", 
                        "ia_court_decision_uncontested_Juvenile", 
                        "ia_court_decision_uncontested_Misc"),
                    
                    "Court Decision - Contested" = 
                      c("ib_court_decision_contested_Consumer_Staff", 
                        "ib_court_decision_contested_Consumer_PAI", 
                        "ib_court_decision_contested_Education_Staff", 
                        "ib_court_decision_contested_Education_PAI", 
                        "ib_court_decision_contested_Employment_Staff", 
                        "ib_court_decision_contested_Employment_PAI", 
                        "ib_court_decision_contested_Family_Staff", 
                        "ib_court_decision_contested_Family_PAI", 
                        "ib_court_decision_contested_Health_Staff", 
                        "ib_court_decision_contested_Health_PAI", 
                        "ib_court_decision_contested_Housing_Staff", 
                        "ib_court_decision_contested_Housing_PAI", 
                        "ib_court_decision_contested_Income_Staff", 
                        "ib_court_decision_contested_Income_PAI", 
                        "ib_court_decision_contested_Individual_Staff", 
                        "ib_court_decision_contested_Individual_PAI", 
                        "ib_court_decision_contested_Juvenile_Staff", 
                        "ib_court_decision_contested_Juvenile_PAI", 
                        "ib_court_decision_contested_Misc_Staff", 
                        "ib_court_decision_contested_Misc_PAI", 
                        "Total_ib_court_decision_contested",
                        "ib_court_decision_contested_Consumer", 
                        "ib_court_decision_contested_Education", 
                        "ib_court_decision_contested_Employment", 
                        "ib_court_decision_contested_Family", 
                        "ib_court_decision_contested_Health", 
                        "ib_court_decision_contested_Housing", 
                        "ib_court_decision_contested_Income", 
                        "ib_court_decision_contested_Individual", 
                        "ib_court_decision_contested_Juvenile", 
                        "ib_court_decision_contested_Misc"),
                    
                    "Court Decision - Appeals" = 
                      c("ic_court_decision_appeals_Consumer_Staff", 
                        "ic_court_decision_appeals_Consumer_PAI", 
                        "ic_court_decision_appeals_Education_Staff", 
                        "ic_court_decision_appeals_Education_PAI", 
                        "ic_court_decision_appeals_Employment_Staff", 
                        "ic_court_decision_appeals_Employment_PAI", 
                        "ic_court_decision_appeals_Family_Staff", 
                        "ic_court_decision_appeals_Family_PAI", 
                        "ic_court_decision_appeals_Health_Staff", 
                        "ic_court_decision_appeals_Health_PAI", 
                        "ic_court_decision_appeals_Housing_Staff", 
                        "ic_court_decision_appeals_Housing_PAI", 
                        "ic_court_decision_appeals_Income_Staff", 
                        "ic_court_decision_appeals_Income_PAI", 
                        "ic_court_decision_appeals_Individual_Staff", 
                        "ic_court_decision_appeals_Individual_PAI", 
                        "ic_court_decision_appeals_Juvenile_Staff", 
                        "ic_court_decision_appeals_Juvenile_PAI", 
                        "ic_court_decision_appeals_Misc_Staff", 
                        "ic_court_decision_appeals_Misc_PAI", 
                        "Total_ic_court_decision_appeals",
                        "ic_court_decision_appeals_Consumer", 
                        "ic_court_decision_appeals_Education", 
                        "ic_court_decision_appeals_Employment", 
                        "ic_court_decision_appeals_Family", 
                        "ic_court_decision_appeals_Health", 
                        "ic_court_decision_appeals_Housing", 
                        "ic_court_decision_appeals_Income", 
                        "ic_court_decision_appeals_Individual", 
                        "ic_court_decision_appeals_Juvenile", 
                        "ic_court_decision_appeals_Misc"),
                    
                    "Other Closure Methods" = 
                      c("k_other_closure_methods_Consumer_Staff", "k_other_closure_methods_Consumer_PAI", 
                        "k_other_closure_methods_Education_Staff", "k_other_closure_methods_Education_PAI", 
                        "k_other_closure_methods_Employment_Staff", "k_other_closure_methods_Employment_PAI", 
                        "k_other_closure_methods_Family_Staff", "k_other_closure_methods_Family_PAI", 
                        "k_other_closure_methods_Health_Staff", "k_other_closure_methods_Health_PAI", 
                        "k_other_closure_methods_Housing_Staff", "k_other_closure_methods_Housing_PAI", 
                        "k_other_closure_methods_Income_Staff", "k_other_closure_methods_Income_PAI", 
                        "k_other_closure_methods_Individual_Staff", "k_other_closure_methods_Individual_PAI", 
                        "k_other_closure_methods_Juvenile_Staff", "k_other_closure_methods_Juvenile_PAI", 
                        "k_other_closure_methods_Misc_Staff", "k_other_closure_methods_Misc_PAI", 
                        "Total_k_other_closure_methods",
                        "k_other_closure_methods_Consumer", "k_other_closure_methods_Education", 
                        "k_other_closure_methods_Employment", "k_other_closure_methods_Family", 
                        "k_other_closure_methods_Health", "k_other_closure_methods_Housing", 
                        "k_other_closure_methods_Income", "k_other_closure_methods_Individual", 
                        "k_other_closure_methods_Juvenile", "k_other_closure_methods_Misc"),
                    
                    "Extensive Services" = 
                      c("l_extensive_services_Consumer_Staff", "l_extensive_services_Consumer_PAI", 
                        "l_extensive_services_Education_Staff", "l_extensive_services_Education_PAI", 
                        "l_extensive_services_Employment_Staff", "l_extensive_services_Employment_PAI", 
                        "l_extensive_services_Family_Staff",  "l_extensive_services_Family_PAI", 
                        "l_extensive_services_Health_Staff", "l_extensive_services_Health_PAI", 
                        "l_extensive_services_Housing_Staff", "l_extensive_services_Housing_PAI", 
                        "l_extensive_services_Income_Staff", "l_extensive_services_Income_PAI", 
                        "l_extensive_services_Individual_Staff", "l_extensive_services_Individual_PAI", 
                        "l_extensive_services_Juvenile_Staff", "l_extensive_services_Juvenile_PAI", 
                        "l_extensive_services_Misc_Staff", "l_extensive_services_Misc_PAI", 
                        "Total_l_extensive_services",
                        "l_extensive_services_Consumer", "l_extensive_services_Education", 
                        "l_extensive_services_Employment", "l_extensive_services_Family", 
                        "l_extensive_services_Health", "l_extensive_services_Housing", 
                        "l_extensive_services_Income", "l_extensive_services_Individual", 
                        "l_extensive_services_Juvenile", "l_extensive_services_Misc"),
                    
                    "N/A" = c("Consumer_Staff", "Consumer_PAI", "Education_Staff", "Education_PAI", 
                                "Employment_Staff", "Employment_PAI", "Family_Staff", "Family_PAI",
                                "Health_Staff", "Health_PAI", "Housing_Staff", "Housing_PAI", 
                                "Income_Staff", "Income_PAI", "Individual_Staff", "Individual_PAI", 
                                "Juvenile_Staff", "Juvenile_PAI", "Misc_Staff", "Misc_PAI", 
                                "Total_PAI", "Total_Staff", "Total_Consumer", "Total_Education", 
                                "Total_Employment", "Total_Family", "Total_Health", "Total_Housing", 
                                "Total_Income", "Total_Individual", "Total_Juvenile", "Total_Misc"),
                    
                    "NA" = c("cases_closed_contested_Consumer_Staff", 
                                "cases_closed_contested_Consumer_PAI", 
                                "cases_closed_contested_Education_Staff", 
                                "cases_closed_contested_Education_PAI", 
                                "cases_closed_contested_Employment_Staff", 
                                "cases_closed_contested_Employment_PAI", 
                                "cases_closed_contested_Family_Staff", 
                                "cases_closed_contested_Family_PAI", 
                                "cases_closed_contested_Health_Staff", 
                                "cases_closed_contested_Health_PAI", 
                                "cases_closed_contested_Housing_Staff", 
                                "cases_closed_contested_Housing_PAI", 
                                "cases_closed_contested_Income_Staff", 
                                "cases_closed_contested_Income_PAI", 
                                "cases_closed_contested_Individual_Staff", 
                                "cases_closed_contested_Individual_PAI", 
                                "cases_closed_contested_Juvenile_Staff", 
                                "cases_closed_contested_Juvenile_PAI", 
                                "cases_closed_contested_Misc_Staff", 
                                "cases_closed_contested_Misc_PAI",
                                "cases_closed_contested_Consumer", 
                                "cases_closed_contested_Education", 
                                "cases_closed_contested_Employment", 
                                "cases_closed_contested_Family", "cases_closed_contested_Health", 
                                "cases_closed_contested_Housing", "cases_closed_contested_Income", 
                                "cases_closed_contested_Individual", 
                                "cases_closed_contested_Juvenile", "cases_closed_contested_Misc")
)